### ISSUE TITLE
404 template

### ISSUE THREAD

**Issue by AndreasVerden** [BlescODev/SimpleCms#8]
The html template which gets rendered if a request returned 404

**Comment by corsinmusic** [comment]
@SimonKindhauser Currently when the json of a page can't be found the server generates an internal server error.
The server should generate an error 404.
This should be fixed or else I can't continue to work on this task.

**Comment by AndreasVerden** [comment]
@CorsinConzett fixed.

**Comment by corsinmusic** [comment]
The 404-Template is now active. The style for the template is pretty basic and might change in the future.
